let Libro = [
    //constructor(titulo, autor, genero, idioma, precio, formato, isbn, descripcion, estado, ubicacion, fecha_publicacion, editorial, paginas, dimensiones, peso) 
    //Libro #1) 
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #2)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #3)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #4)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #5)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #6)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #7)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #8)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #9)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #10)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #11)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #12)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #13)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #14)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #15)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #16)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #17)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #18)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #19)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       //Libro #20)
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
    ]
