let Libro = [
    //constructor(titulo, autor, genero, idioma, precio, formato, isbn, descripcion, estado, ubicacion, fecha_publicacion, editorial, paginas, dimensiones, peso) 
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
       { titulo:titulo,
        autor: autor,
        genero: genero,
        idioma: idioma,
        precio: precio,
        formato: formato,
        isbn: isbn,
        descripcion: descripcion,
        estado: estado,
        ubicacion: ubicacion,
        fecha_publicacion: fecha_publicacion,
        editorial: editorial,
        paginas: paginas,
        dimensiones: dimensiones,
        peso : peso,
       },
    ]
